vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        sending_lists:
            uri_prefix: /files/sending-lists
            upload_destination: "%kernel.project_dir%/public/files/sending_lists"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
